server:
  port: 8086
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartbank_notifications
    username: smartbank
    password: smartbank
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  application:
    name: notification-service
