server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartbank_transactions
    username: smartbank
    password: ${DB_PASSWORD:smartbank}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  application:
    name: transaction-service
